version: '3'
services:
  db:
    image: 'mysql:latest'
    environment:
     - MYSQL_ROOT_PASSWORD=admin123
     - MYSQL_DATABASE=notifications_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  mysql-data: