version: '3'
services:
  db:
    image: 'mysql:latest'
    environment:
     - MYSQL_ROOT_PASSWORD=admin123
     - MYSQL_DATABASE=notifications_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    env_file:
      - .env

volumes:
  mysql-data: