version: '3'
services:
  db:
    image: 'mysql:latest'
    environment:
     - MYSQL_ROOT_PASSWORD=admin123
     - MYSQL_DATABASE=notifications_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
    env_file:
      - .env

volumes:
  mysql-data: